# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths: [apis/user-java/**]
  pull_request:
    branches: [ master ]
    paths: [apis/user-java/**]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file ./apis/user-java/pom.xml
    - name: Create issue on build failure
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: JUnit Report
      # You may pin to the exact commit or the version.
      # uses: mikepenz/action-junit-report@a1848183796ab25257f486396a45968a3e27d387
      uses: mikepenz/action-junit-report@v1.1.1
      with:
        # GITHUB_TOKEN
        github_token: ${{ secrets.GITHUB_TOKEN }}
